---
# tasks file for ipcheck

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['ipcheck', 'ipcheck-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['ipcheck', 'ipcheck-configure']

- name: Ensure ipcheck jobs
  include_tasks: types/job.yml
  vars:
    ipcheck__job: "{{
        outer_item.value
        |combine({'name': outer_item.key})
      }}"
  with_dict: '{{ ipcheck__jobs }}'
  loop_control:
    loop_var: outer_item
  tags: ['ipcheck', 'ipcheck-configure']

- name: Optionally including facts tasks
  include_tasks: facts.yml
  when: ipcheck__facts|bool
  tags: ['ipcheck', 'ipcheck-facts']
